### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by MahleAaronS** [gloverab/confluence-server-to-bookstack-importer#2]
Hi I'm trying to use this tool on windows but I'm getting the following error. 

PS D:\confluence-server-to-bookstack-importer> npm install -loglevel verbose
npm verbose cli D:\Program Files\nodejs\node.exe C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@10.8.2
npm info using node@v20.15.1
npm verbose title npm install
npm verbose argv "install" "-loglevel" "verbose"
npm verbose logfile logs-max:10 dir:C:\Users\vatdev\AppData\Local\npm-cache\_logs\2024-08-06T15_14_58_825Z-
npm verbose logfile C:\Users\vatdev\AppData\Local\npm-cache\_logs\2024-08-06T15_14_58_825Z-debug-0.log
npm verbose stack TypeError: Invalid URL
npm verbose stack     at new URL (node:internal/url:797:36)
npm verbose stack     at getProxy (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\proxy.js:81:10)
npm verbose stack     at getAgent (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\index.js:19:23)
npm verbose stack     at remoteFetch (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\remote.js:38:17)
npm verbose stack     at cacheFetch (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\index.js:16:28)
npm verbose stack     at async fetch (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\fetch.js:98:7)
npm verbose stack     at async RegistryFetcher.packument (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:90:19)
npm verbose stack     at async RegistryFetcher.manifest (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:128:23)
npm verbose stack     at async #fetchManifest (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1199:20)
npm verbose stack     at async #nodeFromEdge (C:\Users\vatdev\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1037:19)
npm error code ERR_INVALID_URL
npm error Invalid URL
npm verbose cwd D:\confluence-server-to-bookstack-importer
npm verbose os Windows_NT 10.0.17763
npm verbose node v20.15.1
npm verbose npm  v10.8.2
npm verbose exit 1
npm verbose code 1
npm error A complete log of this run can be found in: C:\Users\vatdev\AppData\Local\npm-cache\_logs\2024-08-06T15_14_58_825Z-debug-0.log

My .env file looks correct and my application loads
PATH_TO_HTML=./html
ID=OMITTED
SECRET=OMITTED
URL=http://127.0.0.1:8083

I'm on windows server 2019
I'm running the app through xampp
Site is up and running.  
the .env is on the root folder.

**Comment by MahleAaronS** [comment]
Needed to remove proxy settings from my box.
