### ISSUE TITLE
Initial import fails "CSRF Token Mismatch"

### ISSUE THREAD

**Issue by MahleAaronS** [gloverab/confluence-server-to-bookstack-importer#3]
I'm wondering if anyone can help me out.  I'm getting a CSRF token Mismatch error for all of my files.  I validated that my tokens are correct and valid by accessing an api page though postman.    

My .env file with a fake token and secret
URL=http://mysite.us.company:8083/
PATH_TO_HTML=./html
ID=----------------------Omited----------  
SECRET=----------------------Omited----------

  response: {
    status: 419,
    statusText: 'unknown status',
    headers: Object [AxiosHeaders] {
      date: 'Tue, 06 Aug 2024 17:25:21 GMT',
      server: 'Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.2.12',
      vary: 'Authorization',
      'x-powered-by': 'PHP/8.2.12',
      'cache-control': 'no-cache, no-store, private',
      'content-security-policy': "frame-ancestors 'self'; frame-src 'self' https://*.draw.io https://*.youtube.com https://*.youtube-nocookie.com https://*.vimeo.com https://embed.diagrams.net; script-src http: https: 'nonce-Rz4nXNcv5W2Lp2XP9TE7KSZu' 'strict-dynamic'; object-src 'self'; base-uri 'self'",
      expires: 'Sun, 12 Jul 2015 19:01:00 GMT',
      'set-cookie': [Array],
      'keep-alive': 'timeout=5, max=91',
      connection: 'Keep-Alive',
      'transfer-encoding': 'chunked',
      'content-type': 'application/json'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      baseURL: 'http://mysite.us.company:8083/',
      paramsSerializer: [Object],
      method: 'post',
      url: '/books',
      data: '{"name":"Software Teams\\n                        "}',
      'axios-retry': [Object]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '51',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [Socket],
      _header: 'POST /books HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Token yhb9YFjiHrtEGPdkp9ECeuGt1Jz4EJtU:LuLzDEffPn2jZibjWpF9xp7rPerSVLmk\r\n' +
        'User-Agent: axios/1.7.3\r\n' +
        'Content-Length: 51\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: mysite.us.company:8083\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/books',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: 'mysite.us.company',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { message: 'CSRF token mismatch.' }
  }
}
 Software-Teams_32080075.html
 Books created!
 Putting Books on Shelves...
 Books are on the shelves!
 Creating chapters...
D:\confluence-server-to-bookstack-importer\dist\import.js:276
            book_id: parentBook.book
                                ^

TypeError: Cannot read properties of undefined (reading 'book')
    at D:\confluence-server-to-bookstack-importer\dist\import.js:276:33
    at Array.map (<anonymous>)
    at D:\confluence-server-to-bookstack-importer\dist\import.js:257:39
    at Generator.next (<anonymous>)
    at D:\confluence-server-to-bookstack-importer\dist\import.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\confluence-server-to-bookstack-importer\dist\import.js:4:12)
    at createChapters (D:\confluence-server-to-bookstack-importer\dist\import.js:255:30)
    at D:\confluence-server-to-bookstack-importer\dist\import.js:650:15
    at Generator.next (<anonymous>)

**Comment by MahleAaronS** [comment]
My fix was to add /api to my site url.
